Team 1 Playlist Generator/PG.Web/Models/PlaylistViewModel.cs
using PagedList;
using System.Collections.Generic;

namespace PG.Web.Models
{
    public class PlaylistViewModel
    {
        public int Id { get; set; }

        public List<int> DeezerIDs { get; set; }

        public string Title { get; set; }

        public int Duration { get; set; }

        public int Rank { get; set; }

        public string DurationInHours { get; set; }

        public int Fans { get; set; }

        public string PixabayImage { get; set; }

        public bool IsPublic { get; set; }

        public string UserId { get; set; }

        public string CreatorName { get; set; }

        public string LoggedUserId { get; set; }

        public ICollection<SongViewModel> Songs { get; set; } = new List<SongViewModel>();

        public IPagedList<SongViewModel> SongsPaged { get; set; }
    }
}

Team 1 Playlist Generator/PG.Web/Controllers/PlaylistsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PagedList;
using PG.Models;
using PG.Services.Contract;
using PG.Services.DTOs;
using PG.Web.Models;
using PG.Web.Models.Mappers;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PG.Web.Controllers
{
    [Authorize]
    public class PlaylistsController : Controller
    {
        private readonly IPlaylistService _playlistService;
        private readonly IGenreService _genreService;
        private readonly IBingMapsAPIService _bingMapsAPIService;
        private readonly UserManager<User> _userManager;

        public PlaylistsController(IPlaylistService playlistService, IGenreService genreService, IBingMapsAPIService bingMapsAPIService,
            UserManager<User> userManager)
        {
            _playlistService = playlistService;
            _genreService = genreService;
            _bingMapsAPIService = bingMapsAPIService;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(string name = "", string genre = "", string duration = "")
        {
            IEnumerable<PlaylistDTO> playlistsDTOs = await _playlistService.GetAllPlaylistsWithSettings(name, genre, duration);
            IList<PlaylistViewModel> playlistsViewModels = playlistsDTOs
                .Where(x => x.IsPublic)
                .Select(x => x.ToViewModel())
                .ToList();

            var allGenres = await _genreService.GetAllGenres();

            var genresAndDefault = new List<string> { "" };
            genresAndDefault.AddRange(allGenres.Select(x => x.Name));
            ViewBag.Genres = genresAndDefault;

            ViewBag.MinPlaylistDuration = await _playlistService.GetMinPlaylistDuration();
            ViewBag.MaxPlaylistDuration = await _playlistService.GetMaxPlaylistDuration();

            return View(playlistsViewModels);
        }

        public async Task<IActionResult> MyPlaylists()
        {
            IEnumerable<PlaylistDTO> playlistsDTOs = await _playlistService.GetPlaylistsByUser(_userManager.GetUserId(User));
            IList<PlaylistViewModel> playlistsViewModels = playlistsDTOs.Where(x => x.UserId == _userManager.GetUserId(User)).Select(x => x.ToViewModel()).ToList();

            return View(playlistsViewModels);
        }

        public async Task<IActionResult> Create()
        {
            var genresDTOs = await _genreService.GetAllGenres();
            var genresViewModels = genresDTOs.Select(x => x.ToViewModel());
            var playlistGenerator = new PlaylistGeneratorViewModel();

            playlistGenerator.Genres = genresViewModels.ToList();

            return View(playlistGenerator);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PlaylistGeneratorViewModel formInput)
        {
            if (!User.Identity.IsAuthenticated)
            {
                Response.Redirect("Login.aspx");
            }

            int tripTime = await _bingMapsAPIService.FindDuration(formInput.StartLocation, formInput.EndLocation);
            var user = await _userManager.GetUserAsync(User);

            await _playlistService.GeneratePlaylist(tripTime, formInput.PlaylistName,
                formInput.Metal, formInput.Rock, formInput.Pop, formInput.Chalga, formInput.TopTracks, formInput.SameArtist, user);

            return RedirectToAction("MyPlaylists");
        }

        [AllowAnonymous]
        public async Task<IActionResult> Playlist(int id, int pageNumber = 1)
        {
            PlaylistDTO playlistDTO = await _playlistService.GetPlaylistById(id);
            PlaylistViewModel playlistViewModel = playlistDTO.ToViewModel();

            playlistViewModel.SongsPaged = playlistViewModel.Songs.ToPagedList(pageNumber, 13);

            ViewBag.LoggedUserId = _userManager.GetUserId(User);

            return View(playlistViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePlaylist(int id)
        {
            await _playlistService.Delete(id);

            return RedirectToAction("MyPlaylists");
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePublicAccess(int playlistId)
        {
            await _playlistService.UpdatePublicAccess(playlistId);

            return RedirectToAction("Playlist", new { id = playlistId });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var playlist = await _playlistService.GetPlaylistById(id);


            return View(playlist.ToViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PlaylistViewModel model)
        {
            await _playlistService.Update(model.Id, model.ToDTO());

            return RedirectToAction("MyPlaylists");
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult FilterPlaylists(string viewName, string viewGenre, string viewDuration)
        {

            return RedirectToAction("Index",
                new
                {
                    name = viewName,
                    genre = viewGenre,
                    duration = viewDuration,
                });
        }
    }
}

Team 1 Playlist Generator/PG.Web/Views/Playlists/Create.cshtml
@model PlaylistGeneratorViewModel
@{
    ViewData["Title"] = "Create";
}

<div class="d-flex flex-column align-items-center">
    <form asp-controller="Playlists" asp-action="Create" method="post" id="form-playlist">
        <div class="d-flex flex-column align-items-center card mt-5">
            <div class="card-body">
                <h5 class="rounded" id="generate-playlist-topleft">
                    Generate playlist
                </h5>

                <p class="card-text">Travel Information:</p>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <p class="input-group-text">From:</p>
                        <input asp-for="@Model.StartLocation" type="text" class="form-control" aria-describedby="button-addon2" required /> @*id="search_input"*@
                    </div>
                    <span asp-validation-for="@Model.StartLocation" class="text-danger"></span> @*id="search_input2"*@
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <p class="input-group-text">To:</p>
                        <input asp-for="@Model.EndLocation" type="text" class="form-control" aria-describedby="button-addon2" required>
                    </div>
                    <span asp-validation-for="@Model.EndLocation" class="text-danger"></span>
                </div>
                <div class="form-group" id="no-margin-bottom">
                    <label asp-for="@Model.PlaylistName"></label>
                    <input asp-for="@Model.PlaylistName" class="form-control" required />
                    <span asp-validation-for="@Model.PlaylistName" class="text-danger"></span>
                </div>
                <div>
                    <span>Metal:   </span>
                    <input type="range" id="rangeInput" asp-for="@Model.Metal" min="@ViewBag.MinPlaylistDuration" max="@ViewBag.MaxPlaylistDuration" step="1"
                           oninput="amount.value=rangeInput.value + '%'">
                    <output id="amount" name="amount" for="rangeInput sec">0 %</output>
                </div>
                <div>
                    <span>Rock:    </span>
                    <input type="range" id="rangeInput2" asp-for="@Model.Rock" min="@ViewBag.MinPlaylistDuration" max="@ViewBag.MaxPlaylistDuration" step="1"
                           oninput="amount2.value=rangeInput2.value + '%'">
                    <output id="amount2" name="amount2" for="rangeInput2 sec">0 %</output>
                </div>
                <div>
                    <span>Pop:     </span>
                    <input type="range" id="rangeInput3" asp-for="@Model.Pop" min="@ViewBag.MinPlaylistDuration" max="@ViewBag.MaxPlaylistDuration" step="1"
                           oninput="amount3.value=rangeInput3.value + '%'">
                    <output id="amount3" name="amount3" for="rangeInput3 sec">0 %</output>
                </div>
                <div id="last-genre">
                    <span>Pop-Folk:</span>
                    <input type="range" id="rangeInput4" asp-for="@Model.Chalga" min="@ViewBag.MinPlaylistDuration" max="@ViewBag.MaxPlaylistDuration" step="1"
                           oninput="amount4.value=rangeInput4.value + '%'">
                    <output id="amount4" name="amount4" for="rangeInput4 sec">0 %</output>
                </div>
                <span id="top-tracks">Top tracks:</span>
                @Html.EditorFor(x => x.TopTracks)

                <span id="same-artist">Same artist:</span>
                @Html.EditorFor(x => x.SameArtist)
            </div>
            <button type="submit" class="btn btn-dark" id="button-playlist-form">Generate</button>
        </div>
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


<script>


    $('input[type=range]').wrap("<div class='range'></div>");
    var i = 1;

    $('.range').each(function () {
        var n = this.getElementsByTagName('input')[0].value;
        var x = (n / 100) * (this.getElementsByTagName('input')[0].offsetWidth - 8) - 12;
        this.id = 'range' + i;
        if (this.getElementsByTagName('input')[0].value == 0) {
            this.className = "range"
        } else {
            this.className = "range rangeM"
        }
        this.innerHTML += "<style>#" + this.id + " input[type=range]::-webkit-slider-runnable-track {background:linear-gradient(to right, #b1872d 0%, #b1872d " + n + "%, #515151 " + n + "%)} #" + this.id + ":hover input[type=range]:before{content:'" + n + "'!important;left: " + x + "px;} #" + this.id + ":hover input[type=range]:after{left: " + x + "px}</style>";
        i++
    });

    $('input[type=range]').on("input", function () {
        var a = this.value;
        var p = (a / 100) * (this.offsetWidth - 8) - 12;
        if (a == 0) {
            this.parentNode.className = "range"
        } else {
            this.parentNode.className = "range rangeM"
        }
        this.parentNode.getElementsByTagName('style')[0].innerHTML += "#" + this.parentNode.id + " input[type=range]::-webkit-slider-runnable-track {background:linear-gradient(to right, #b1872d 0%, #b1872d " + a + "%, #515151 " + a + "%)} #" + this.parentNode.id + ":hover input[type=range]:before{content:'" + a + "'!important;left: " + p + "px;} #" + this.parentNode.id + ":hover input[type=range]:after{left: " + p + "px}";
    })
</script>

Team 1 Playlist Generator/PG.Web/Views/Playlists/Edit.cshtml
@model PlaylistViewModel

<div class="row" style="margin-left: 25vw;">
    <div class="col-md-4" >
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group row">
                <label asp-for="Title" class="col-md-6 col-form-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="PixabayImage" class="col-md-6 col-form-label"></label>
                <input asp-for="PixabayImage" class="form-control" />
                <span asp-validation-for="PixabayImage" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <form class="form-group row" method="post" asp-controller="Playlists" asp-action="DeletePlaylist">
                <input type="hidden" name="id" value="@Model.Id" />
                <div class="form__buttons buttons">
                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                </div>
            </form>
            <form class="form-group row" method="post" asp-controller="Playlists" asp-action="UpdatePublicAccess">
                @if (Model.IsPublic)
                {
                    <input type="hidden" name="playlistId" value="@Model.Id" />
                    <div class="form__buttons buttons">
                        <button type="submit" class="btn btn-outline-dark">Make Private</button>
                    </div>
                }
                else
                {
                    <input type="hidden" name="playlistId" value="@Model.Id" />
                    <div class="form__buttons buttons">
                        <button type="submit" class="btn btn-outline-dark">Make Public</button>
                    </div>
                }
            </form>
        </div>
    </div>
</div>

Team 1 Playlist Generator/PG.Web/Views/Playlists/Index.cshtml
@model IList<PlaylistViewModel>
@{
    ViewData["Title"] = "Index";
}
<div class="form" style="font-family: 'Arial Black', Gadget, sans-serif;">
    <form class="formSearch" method="post" asp-controller="Playlists" asp-action="FilterPlaylists" style="margin-bottom:30px">


        <input name="viewName" placeholder="Search.." value="" />

        @Html.DropDownList("viewGenre", new SelectList(ViewBag.Genres))

        <div>
            <span >Duraton max range:</span>
            <input type="range" id="rangeInput" name="viewDuration" min="@ViewBag.MinPlaylistDuration" max="@ViewBag.MaxPlaylistDuration" step="1"
                   oninput="amount.value=rangeInput.value + ' sec'">
            <output id="amount" name="amount" for="rangeInput sec">@ViewBag.MaxPlaylistDuration sec</output>
        </div>

        <div class="form__buttons buttons" >
            <button type="submit" class="btn btn-outline-dark">Search</button>
        </div>

    </form>
</div>

<partial name="_DisplayPlaylists" model="Model">


    <style>
        .range {
            display: inline-block;
            margin: 36px 20px 20px
        }

        input[type=range] {
            -webkit-appearance: none;
            position: relative
        }

            input[type=range]::-webkit-slider-runnable-track {
                width: 300px;
                height: 2px;
                border: none;
                border-radius: 3px
            }

            input[type=range]::-webkit-slider-thumb {
                -webkit-appearance: none;
                border: none;
                height: 12px;
                width: 12px;
                border-radius: 510%;
                background: #141414;
                border: 2px solid #515151;
                margin-top: -5px;
                cursor: pointer
            }

        .focused::-webkit-slider-thumb {
            box-shadow: 0 0 0 10px rgba(255, 255, 255, 0.15)
        }

        .clicked::-webkit-slider-thumb {
            -webkit-transform: scale(1.5)
        }

        .disabled::-webkit-slider-thumb {
            -webkit-transform: scale(0.9);
            box-shadow: 0 0 0 3px #141414;
            background: #515151 !important;
            border-color: #515151 !important
        }

        input[type=range]:focus {
            outline: none
        }

        .rangeM input[type=range].disabled::-webkit-slider-runnable-track {
            background: #515151 !important
        }

        .rangeM input[type=range]::-webkit-slider-thumb {
            background: #393436;
            border-color: #393436
        }

        .range:hover input[type=range]:before {
            color: white;
            content: '50';
            position: absolute;
            font-family: Roboto Slab;
            top: -49px;
            background: #393436;
            padding: 8px 0 3px;
            font-size: 14px;
            width: 30px;
            text-align: center;
            border-radius: 100% 100% 0 0
        }

        .range:hover input[type=range]:after {
            content: '';
            position: absolute;
            top: -19px;
            left: 50px;
            border-left: 15px solid transparent;
            border-right: 15px solid transparent;
            border-top: 8px solid #393436;
            font-family: Roboto Slab
        }
    </style>


    <script>
        $('input[type=range]').wrap("<div class='range'></div>");
        var i = 1;

        $('.range').each(function () {
            var n = this.getElementsByTagName('input')[0].value;
            var x = (n / 100) * (this.getElementsByTagName('input')[0].offsetWidth - 8) - 12;
            this.id = 'range' + i;
            if (this.getElementsByTagName('input')[0].value == 0) {
                this.className = "range"
            } else {
                this.className = "range rangeM"
            }
            this.innerHTML += "<style>#" + this.id + " input[type=range]::-webkit-slider-runnable-track {background:linear-gradient(to right, #b1872d 0%, #b1872d " + n + "%, #515151 " + n + "%)} #" + this.id + ":hover input[type=range]:before{content:'" + n + "'!important;left: " + x + "px;} #" + this.id + ":hover input[type=range]:after{left: " + x + "px}</style>";
            i++
        });

        $('input[type=range]').on("input", function () {
            var a = this.value;
            var p = (a / 100) * (this.offsetWidth - 8) - 12;
            if (a == 0) {
                this.parentNode.className = "range"
            } else {
                this.parentNode.className = "range rangeM"
            }
            this.parentNode.getElementsByTagName('style')[0].innerHTML += "#" + this.parentNode.id + " input[type=range]::-webkit-slider-runnable-track {background:linear-gradient(to right, #b1872d 0%, #b1872d " + a + "%, #515151 " + a + "%)} #" + this.parentNode.id + ":hover input[type=range]:before{content:'" + a + "'!important;left: " + p + "px;} #" + this.parentNode.id + ":hover input[type=range]:after{left: " + p + "px}";
        })
    </script>

Team 1 Playlist Generator/PG.Web/Views/Playlists/MyPlaylists.cshtml
@model IList<PlaylistViewModel>
@{
    ViewData["Title"] = "View";
}

<partial name="_DisplayPlaylists" model="Model">

Team 1 Playlist Generator/PG.Web/Views/Playlists/Playlist.cshtml
@inject IJsonHelper Json
@model PlaylistViewModel

<div class="baseGrid">
    <div class="aboutPlaylist">
        <div class="aboutWrapper">
            <div>
                <h1>@Model.Title</h1>
                <div class="album-name2Playlist">
                    <p><ion-icon name="radioPlaylist"></ion-icon> &nbsp;<span>By: @Model.CreatorName</span></p>

                    <p><ion-icon name="radioPlaylist"></ion-icon> &nbsp;<span>Rank: @Model.Rank</span></p>
                </div>
            </div>
            <div style="display:flex; flex-direction: column;">
                @if (ViewBag.LoggedUserId != null && ViewBag.LoggedUserId == Model.UserId)
                {
                    <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                }
                @if (User.IsInRole("Admin"))
                {
                    <form class="form" method="post" asp-controller="Playlists" asp-action="DeletePlaylist" style="margin-bottom:30px">
                        <input type="hidden" name="id" value="@Model.Id" />
                        <div class="form__buttons buttons">
                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                        </div>
                    </form>
                }
            </div>
        </div>
        <div class="pages">
            @for (int i = 0; i < Model.SongsPaged.PageCount; i++)
            {
                var num = i + 1;

                <a href="#" onclick="LoadPlaylistPage(@Model.Id, @num)">@num</a>
            }
        </div>
        <div id="playlistInfo">
            <table class="table table-striped">
                <partial name="_PlaylistDetails" model="Model.SongsPaged">
            </table>
        </div>
    </div>

    <div class="right-column">
        <div id="dz-root"></div>
        <div id="player"></div>
    </div>
</div>


<script>

function LoadPlaylistPage(id, pageNumber) {
        var url = '@Url.Action("Playlist","Playlists")' + '?id=' + id + '&pageNumber=' + pageNumber;

        $.get(url, function (response) {
            var result = $(response).find('#playlistInfo');

            $('#playlistInfo').html(result);
        });
    }

    $(document).ready(function () {

        $("#controlers input").attr('disabled', true);
        $("#slider_seek").click(function (evt, arg) {
            var left = evt.offsetX;
            DZ.player.seek((evt.offsetX / $(this).width()) * 100);
        });
    });

    function event_listener_append() {
        var pre = document.getElementById('event_listener');
        var line = [];
        for (var i = 0; i < arguments.length; i++) {
            line.push(arguments[i]);
        }
        pre.innerHTML += line.join(' ') + "\n";
    }

    function onPlayerLoaded() {
            DZ.player.playTracks(@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.DeezerIDs) as String), false);
        $("#controlers input").attr('disabled', false);
        event_listener_append('player_loaded');
        DZ.Event.subscribe('current_track', function (arg) {
            event_listener_append('current_track', arg.index, arg.track.title, arg.track.album.title);
        });
        DZ.Event.subscribe('player_position', function (arg) {
            event_listener_append('position', arg[0], arg[1]);
            $("#slider_seek").find('.bar').css('width', (100 * arg[0] / arg[1]) + '%');
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        DZ.init({
            appId: '8',
            channelUrl: 'https://developers.deezer.com/examples/channel.php',
            player: {
                container: 'player',
                playlist: true,
                width:  957,
                height: 760,
                onload: onPlayerLoaded
            }
        });
    });


    TweenMax.from(".aboutPlaylist", 1, {
        delay: 0.2,
        y: 20,
        opacity: 0,
        ease: Expo.easeInOut
    })

    TweenMax.from(".album-name2Playlist", 2, {
        delay: 1.5,
        y: 20,
        opacity: 0,
        ease: Expo.easeInOut
    })

    TweenMax.from(".right-column", 1, {
        delay: 0.2,
        y: 20,
        opacity: 0,
        ease: Expo.easeInOut
    })
</script>

Team 1 Playlist Generator/PG.Web/Views/Playlists/_PlaylistDetails.cshtml
@model IPagedList<SongViewModel>


@foreach (var song in Model)
{
    <tbody>
        <th>@song.Title</th>
        <td>@song.DurationInMinutes</td>
        <td>
            <a href="@song.Preview">Link </a>
        </td>
    </tbody>
}